eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  zipkin:
    base-url: http://localhost:9211
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: service-rpc1
  redis:
    host: localhost
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 0
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: true
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    logSlowSql: true
feign:
  hystrix:
    enabled: true
    config:
      stream:
        maxConcurrentConnections: 50
management:
  security:
    enabled: false
logging:
  file: D:\logback\${spring.application.name}-${server.port}.log