eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
  tomcat: 
    max-threads: 128
    min-spare-threads: 64
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9211
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  max:
    host:
      connections: 500
  host:
#    socket-timeout-millis: 6000
#    connect-timeout-millis: 6000
    maxTotalConnections: 200
    maxPerRouteConnections: 10
  routes:
    servic-rpc-a:
      path: /service-rpc-a/**
      serviceId: service-rpc1
      sensitiveHeaders:
    servic-rpc-b:
      path: /service-rpc-b/**
      serviceId: service-rpc2
      sensitiveHeaders:
  ribbonIsolationStrategy: THREAD
  threadPool:
    useSeparateThreadPools: true
hystrix:
  enabled: true
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        strategy: THREAD          # SEMAPHORE/THREAD
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
service-rpc1:
  ribbon: 
    ReadTimeout: 1000
    ConnectTimeout: 500
    eager-load:
      enabled: true
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 1
service-rpc2:
  ribbon: 
    ReadTimeout: 1000 
    ConnectTimeout: 500
    eager-load:
      enabled: true
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 1
management:
  security:
    enabled: false
logging:
  file: D:\logback\${spring.application.name}-${server.port}.log
    